root: tmp  #  The root directory to which the experiment belongs (should not be set)
name: a #  The name of the experiment (should not be set)
status: created #  The status of the experiment (one of ['default' | 'created' | 'running' | 'error' | 'finished'])
created: 05:59PM September 17, 2019 #  The date the experiment was created (should not be set)
purpose: '' #  The purpose for the experiment (should not be set)
messages: {} #  A dictionary of messages which are able to vary throughout the experiment (should not be set)
git: {} #  A dictionary containing the git history corresponding to the defaults.yml file. Only
definition: #  Of the form ``{'path'
  path: ''
  class: AnExperiment
a: h #  A parameter (default='h')
b: 17 #  Another parameter (default=17)
